name: Build

on:
  push:
    branches: [ "proton_7.0" ]
  pull_request:
    branches: [ "proton_7.0" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: brew install wget mingw-w64 cmake nasm libtool automake meson glslang
    - name: inspecting python
      run: echo /usr/local/lib/python3.*/site-packages/mesonbuild/scripts/depfixer.py || exit 1
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
