name: Build

on:
  push:
    branches: [ "proton_7.0" ]
  pull_request:
    branches: [ "proton_7.0" ]

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: install packages
      run: brew install wget mingw-w64 cmake nasm libtool automake meson glslang
    - name: build
      run: ./build_proton.sh
      
